In [3]:
import torch
print(torch.cuda.is_available())

False

In [2]:
import pandas as pd
import torch

### **Dealing with the dataset**

In [5]:
df = pd.read_csv('data/fra.txt',sep = '\t')

In [6]:
df.head()

,Go.,Va !,CC-BY 2.0 (France) Attribution: tatoeba.org #2877272 (CM) & #1158250 (Wittydev)
0,Go.,Marche.,CC-BY 2.0 (France) Attribution: tatoeba.org #2...
1,Go.,En route !,CC-BY 2.0 (France) Attribution: tatoeba.org #2...
2,Go.,Bouge !,CC-BY 2.0 (France) Attribution: tatoeba.org #2...
3,Hi.,Salut !,CC-BY 2.0 (France) Attribution: tatoeba.org #5...
4,Hi.,Salut.,CC-BY 2.0 (France) Attribution: tatoeba.org #5...

In [7]:
df = df.iloc[:,:-1]

In [8]:
df.sample(10)

,Go.,Va !
167797,We left home early in the morning.,Nous quittâmes la maison de bon matin.
213595,I won't be spending Christmas with my family.,Je ne passerai pas Noël avec ma famille.
14261,You seem smart.,Vous avez l'air intelligente.
77685,"In the end, Tom gave up.",Tom a fini par céder.
182278,I didn't know that you were so tired.,Je ne savais pas que tu étais si fatiguée.
227177,I got a stomach tumor and had to have it opera...,J'ai eu une tumeur de l'estomac et j'ai dû la ...
35879,It was really dark.,C'était vraiment sombre.
50989,I'll keep it with me.,Je vais le garder avec moi.
180409,We're not lost. I know where we are.,Nous ne nous sommes pas perdus. Je sais où nou...
176251,He was in favor of equality for all.,Il était en faveur de l'égalité pour tous.

In [9]:
df.to_csv('data/Eng-Fra.csv',index = False)

In [10]:
df = pd.read_csv('data/Eng-Fra.csv')
df.head()

  English      French
0     Go.        Va !
1     Go.     Marche.
2     Go.  En route !
3     Go.     Bouge !
4     Hi.     Salut !

In [11]:
df.columns

Index(['English', 'French'], dtype='object')

In [12]:
df.shape

(239189, 2)

### **Preprocessing**

In [13]:
from preprocessing.normalize import normalize_text

df['English'] = df['English'].apply(normalize_text)
df['French'] = df['French'].apply(normalize_text)

In [14]:
df.head()

  English    French
0      go        va
1      go    marche
2      go  en route
3      go     bouge
4      hi     salut

### **Vocabulary Building**

In [15]:
from preprocessing.vocabulary import Vocabulary

eng_vocab = Vocabulary('english')
fr_vocab = Vocabulary('french')

In [18]:
for eng, fr in zip(df['English'], df['French']):
    eng_vocab.add_sentence(eng)
    fr_vocab.add_sentence(fr)

In [19]:
print("Engish Vocabulary Size: ",eng_vocab.vocab_size)
print("French Vocabulary Size: ",fr_vocab.vocab_size)

Engish Vocabulary Size:  4
French Vocabulary Size:  4

In [8]:
from preprocessing.sentence_to_tensor import sentence_to_tensor
print("English")
print("Input: i am cold")
tensor_eng = sentence_to_tensor(eng_vocab,'i am cold')
print("Tensor: ",tensor_eng)
print("Tensor Shape: ",tensor_eng.shape)
print("Tensor Datatype: ",tensor_eng.dtype)
print('\n------------------\n')
print("French")
print("Input: je suis froid")
tensor_fr = sentence_to_tensor(fr_vocab,'je suis froid')
print("Tensor: ",tensor_fr)
print("Tensor Shape: ",tensor_fr.shape)
print("Tensor Datatype: ",tensor_fr.dtype)

English
Input: i am cold
Tensor:  tensor([ 19, 150, 207,   1])
Tensor Shape:  torch.Size([4])
Tensor Datatype:  torch.int64

------------------

French
Input: je suis froid
Tensor:  tensor([ 46, 106, 545,   1])
Tensor Shape:  torch.Size([4])
Tensor Datatype:  torch.int64

In [8]:
# verifying word mapping
print("English Vocabulary")
print(eng_vocab.index2word[19])
print(eng_vocab.index2word[150])
print(eng_vocab.index2word[207])
print(eng_vocab.index2word[1])
print('---------------------',end = '\n')
print("French Vocabulary")
print(fr_vocab.index2word[46])
print(fr_vocab.index2word[106])
print(fr_vocab.index2word[545])
print(fr_vocab.index2word[1])

English Vocabulary
i
am
cold
EOS
---------------------
French Vocabulary
je
suis
froid
EOS

### **The Encoder Part**

In [9]:
from models.encoder import Encoder

encoder = Encoder(vocab_size = eng_vocab.vocab_size, embedding_dim = 256, hidden_size = 512)
input_tensor = sentence_to_tensor(eng_vocab,'i am cold')
input_tensor = input_tensor.unsqueeze(0) # adds a batch dimension

encoder_outputs, encoder_hidden = encoder(input_tensor)

In [10]:
print("Input shape:", input_tensor.shape)
print("Encoder outputs shape:", encoder_outputs.shape)
print("Hidden shape:", encoder_hidden.shape)

Input shape: torch.Size([1, 4])
Encoder outputs shape: torch.Size([1, 4, 512])
Hidden shape: torch.Size([1, 1, 512])

In [11]:
print(encoder_outputs)

tensor([[[-0.1357, -0.1254, -0.3636,  ...,  0.4629,  0.0756,  0.1026],
         [-0.3123, -0.2231, -0.3111,  ...,  0.5390,  0.1992,  0.2579],
         [-0.5360,  0.3281, -0.2878,  ...,  0.2897,  0.1088, -0.2709],
         [-0.3123,  0.1545, -0.1856,  ...,  0.2229,  0.0497, -0.0057]]],
       grad_fn=<TransposeBackward1>)

In [13]:
print(encoder_hidden)

tensor([[[-3.1300e-01, -4.0522e-01,  1.7142e-02, -4.9370e-01, -2.4274e-01,
          -9.2513e-02,  1.5109e-01,  1.8159e-01, -2.0438e-01, -1.3095e-01,
          -6.0902e-02, -2.6568e-01,  2.2976e-01, -3.4767e-01,  3.9308e-01,
           3.5519e-01,  3.3935e-01,  6.5468e-02,  3.2292e-01, -4.0314e-01,
          -2.4842e-01,  2.9810e-01,  5.0345e-02,  2.0033e-01,  2.9292e-01,
           3.1641e-01,  9.5965e-04,  1.5583e-01,  2.0398e-01,  1.8466e-01,
          -1.8714e-01,  3.1300e-02, -3.2667e-01,  1.4779e-02,  1.3582e-02,
           5.2242e-02,  9.4495e-02,  3.4118e-01,  1.2148e-01, -6.6933e-02,
          -2.8573e-01,  6.7898e-02,  4.9664e-02,  6.9269e-02,  2.1963e-01,
          -8.3857e-02, -1.5241e-01,  2.2065e-02,  3.7159e-01,  7.7296e-02,
          -1.2733e-01, -3.1591e-01,  2.4678e-01, -5.4763e-01,  4.3765e-01,
          -2.4264e-02,  1.6785e-01, -2.0082e-01,  8.0485e-02, -6.2078e-02,
           1.3713e-01, -8.4408e-02,  9.6767e-02,  1.5436e-01,  1.3192e-01,
           2.0021e-01, -2.3558e-02, -3.1678e-01,  3.2424e-01, -2.6744e-01,
           2.2341e-01,  4.6451e-02, -2.5317e-01,  5.5973e-02, -4.5422e-01,
           2.3582e-01,  1.3878e-01, -5.3355e-03, -1.4077e-01, -1.9846e-01,
          -7.3114e-02,  7.9179e-02,  2.0396e-02,  4.8607e-02, -7.4410e-03,
           1.7866e-01, -1.0682e-01, -2.7890e-01, -3.5253e-01, -1.0805e-01,
           5.3220e-02, -1.0550e-01,  1.3735e-01,  1.9815e-02, -1.3849e-01,
          -1.6988e-01, -1.1427e-01, -1.2723e-01, -1.3010e-02, -4.3191e-01,
           7.2226e-02,  3.1654e-01, -1.7110e-01, -1.8009e-01, -8.7333e-04,
          -1.0037e-01,  8.8171e-02, -3.6400e-01, -2.4438e-02,  3.5698e-01,
          -3.1881e-01, -9.5347e-02,  2.6321e-01,  2.1105e-01, -1.6805e-01,
          -2.1463e-02, -2.3089e-01, -1.5067e-01, -2.1665e-01, -2.2563e-01,
           2.1259e-01,  2.0637e-01, -2.5124e-01,  6.2857e-02, -2.3287e-01,
          -2.0845e-01,  2.3013e-02,  4.7857e-02,  9.1798e-03, -4.7700e-03,
          -4.2146e-02,  1.2751e-01, -2.5143e-02,  3.6032e-02,  5.9668e-02,
           1.8286e-02,  2.6833e-01, -2.9592e-01, -2.1420e-01, -3.9320e-01,
          -1.7987e-01, -1.6675e-01,  5.0044e-02, -5.5622e-02,  4.4375e-01,
           2.2999e-01, -1.2829e-01, -2.5413e-02, -2.1740e-02, -2.3007e-01,
          -2.4200e-01,  6.6943e-02, -1.5796e-01, -2.7005e-01,  1.7992e-01,
          -9.3765e-02,  3.7492e-01,  2.8887e-01, -2.2050e-01, -1.0801e-02,
          -4.3932e-01, -1.9707e-01, -2.6795e-02, -9.6944e-02,  4.4322e-01,
           9.8686e-04,  2.2907e-01,  8.4873e-02,  1.2607e-01, -3.1239e-01,
           1.9941e-01,  5.0204e-01,  2.3089e-01, -7.1331e-02, -8.6517e-02,
           1.0740e-01, -4.4204e-02, -2.9450e-01,  5.0752e-02, -1.4919e-01,
           3.1452e-01, -1.1777e-01,  5.4687e-02,  1.9133e-01,  3.3565e-01,
           2.3125e-01,  3.8091e-01, -2.2535e-01,  7.4636e-02, -2.9519e-02,
           2.5401e-01,  7.5697e-02,  2.4088e-02,  3.9047e-02, -1.2104e-01,
          -8.8922e-02, -4.6446e-02,  1.1673e-01,  1.1313e-02,  2.5453e-01,
          -2.9051e-01,  3.4034e-01, -1.3402e-02,  5.1138e-01,  2.0839e-01,
           3.0547e-01, -2.4641e-01,  9.0125e-03,  1.6721e-01, -2.9958e-01,
          -2.4044e-01,  2.1644e-01, -2.5834e-01, -6.6611e-02,  1.2953e-01,
           1.2096e-01, -2.0145e-02, -4.0835e-02, -3.5243e-01,  2.3128e-01,
           2.6928e-01, -1.7306e-01, -1.0324e-01, -1.2933e-03, -2.1389e-01,
          -7.5981e-02, -5.1893e-02,  1.4396e-01, -9.1884e-02,  4.3573e-02,
          -6.4754e-02, -3.0595e-01,  9.9155e-02, -2.0821e-01,  6.5511e-02,
          -2.3609e-01,  2.1297e-01, -1.7983e-01, -1.3023e-01, -4.8117e-01,
           1.8722e-01, -3.3646e-02,  3.7960e-01, -2.4805e-02,  5.6117e-02,
          -5.4516e-02, -5.5219e-01, -1.2711e-01, -2.6493e-01,  4.1128e-01,
          -3.9176e-02,  2.4448e-01, -2.9669e-01,  4.6119e-02,  3.7541e-01,
           4.7512e-01,  1.7827e-01,  1.7419e-02, -2.3074e-01, -2.8654e-03,
           1.3437e-01,  8.3904e-02,  5.0188e-02, -1.1265e-01,  5.5662e-02,
           3.0880e-01, -2.4813e-01, -2.1593e-01,  1.8726e-01,  1.2267e-01,
           1.9941e-01,  1.5784e-01, -1.2550e-01, -1.1324e-01, -5.2134e-02,
          -8.1149e-02,  1.4265e-01,  1.1954e-01, -5.4599e-02,  3.3544e-01,
           1.6089e-01,  2.2729e-01,  1.6678e-01, -2.6538e-01,  2.5314e-01,
           3.3477e-02, -2.0237e-02, -3.8286e-03,  3.2063e-01,  5.3284e-02,
           2.4245e-01,  2.8519e-01, -5.5464e-03,  5.5466e-02, -6.0856e-02,
           3.1029e-01, -4.1633e-01, -1.7535e-01, -9.3000e-02, -1.3729e-01,
           7.3363e-03, -1.6577e-01, -6.8887e-02,  1.2558e-01,  5.0474e-01,
          -2.0594e-01, -1.7403e-01,  2.6249e-01,  2.5294e-01,  2.4510e-01,
           3.1928e-01, -1.3076e-01, -8.0408e-02, -3.6356e-02,  2.6240e-02,
           9.5745e-02,  8.0138e-02, -1.9173e-01,  1.5144e-01,  6.5329e-02,
           3.5481e-02, -1.5074e-01, -4.1166e-01,  3.2776e-03,  3.1945e-01,
          -1.4734e-01, -2.4472e-01,  4.4835e-01,  5.3728e-02,  1.3350e-01,
           2.9842e-01, -1.2137e-01,  6.1629e-02, -1.3635e-01,  9.2298e-02,
          -7.4522e-02, -4.7883e-01, -6.2304e-02, -2.3923e-01,  2.0672e-02,
          -1.0116e-01,  1.7189e-01,  3.4734e-01, -1.4257e-01, -1.2647e-01,
          -3.4645e-02,  4.2875e-03, -3.2891e-02,  3.5719e-02,  8.9133e-02,
           2.1277e-01, -1.0865e-01,  2.0927e-02,  1.5656e-01,  3.5128e-01,
           2.6870e-01,  2.2510e-01,  1.6263e-01, -3.1609e-01, -1.4649e-02,
           2.8610e-01,  1.9653e-02,  1.0743e-01,  4.5964e-02, -1.6735e-01,
           6.0383e-02, -1.6407e-01, -9.5267e-02, -2.5053e-01, -1.7142e-01,
           2.6889e-01, -2.7352e-01, -1.7494e-02, -3.1244e-01, -1.4869e-02,
           2.4516e-01, -3.1351e-01, -1.8185e-01, -2.0188e-01, -3.3173e-01,
          -6.4076e-03,  3.0850e-01, -1.5370e-01,  3.1869e-01, -1.3010e-01,
           1.3150e-01,  2.0711e-01,  8.0941e-02,  3.1293e-01,  1.9355e-01,
           2.4794e-01,  1.1152e-01,  1.3234e-01, -2.9302e-01,  5.1454e-02,
          -8.5197e-02,  6.3656e-03, -2.9603e-01,  4.4683e-03,  2.2106e-02,
          -2.7588e-02,  3.3857e-01,  1.6815e-01,  3.2404e-01,  2.5991e-01,
          -5.2863e-01, -2.7558e-01,  1.7010e-01,  1.6876e-01, -5.2170e-01,
          -1.8242e-01, -9.2013e-02, -3.8762e-01, -2.7351e-01, -2.7511e-01,
           8.9184e-02,  2.5290e-02,  7.3851e-02, -2.5988e-01, -1.2294e-01,
          -2.4531e-02, -9.4412e-02,  1.4913e-01, -2.1050e-01, -3.3420e-01,
          -3.5388e-01, -8.7839e-02,  1.4903e-01, -3.0303e-01,  2.4561e-01,
          -8.0844e-02,  2.5281e-01, -1.3429e-01,  2.1222e-01,  1.2483e-01,
          -3.2328e-01, -3.3541e-02, -6.6835e-02, -2.8992e-01, -3.9517e-01,
          -2.8635e-01, -1.0137e-01, -2.2376e-01,  1.3700e-01,  4.1285e-01,
           1.3022e-01, -4.0737e-01, -3.3137e-01,  7.5537e-03,  2.7139e-02,
           3.2491e-01, -2.7677e-01, -1.0909e-01, -1.5704e-01,  5.4822e-02,
          -7.0070e-02,  2.0850e-01, -1.7020e-01, -1.9218e-01,  5.5202e-02,
          -3.7799e-02, -3.2083e-01, -1.1390e-01, -3.1175e-01,  3.0886e-02,
           1.5830e-02,  5.0350e-02, -1.9924e-01, -1.2304e-01,  4.0812e-02,
          -3.2005e-01,  1.3019e-01, -1.4219e-01,  5.2543e-01, -1.7710e-01,
          -2.1324e-01,  4.7266e-05,  1.4604e-01, -2.2393e-01, -1.0885e-01,
          -3.8718e-01, -5.0489e-01, -1.8600e-01, -1.2805e-01, -2.0153e-01,
           4.1678e-02, -2.3320e-01, -1.4529e-01,  7.0914e-02,  1.9216e-02,
          -1.7684e-01,  1.5237e-01, -1.1930e-01,  1.3845e-01, -1.8361e-01,
           8.4817e-03, -2.4564e-01, -2.9607e-01, -2.3665e-01, -2.0634e-01,
          -2.3771e-01, -4.3826e-02,  1.7368e-01,  6.7946e-02,  8.0811e-02,
          -1.8894e-01, -1.6635e-01, -1.5843e-01, -1.4882e-01,  9.2308e-02,
           1.1490e-01, -2.3901e-01]]], grad_fn=<StackBackward0>)

### **The Decoder Part**

In [11]:
from models.decoder import Decoder

decoder = Decoder(vocab_size = fr_vocab.vocab_size, embedding_dim = 256, hidden_size = 512)
decoder_input = torch.tensor([[fr_vocab.word2index['SOS']]])
decoder_output, decoder_hidden = decoder(decoder_input, encoder_hidden)

In [12]:
print("Decoder output shape:", decoder_output.shape)
print("Decoder hidden shape:", decoder_hidden.shape)

Decoder output shape: torch.Size([1, 1, 35321])
Decoder hidden shape: torch.Size([1, 1, 512])

In [13]:
predicted_token = decoder_output.argmax(-1)
print(predicted_token)

tensor([[33061]])

In [14]:
print(fr_vocab.index2word[predicted_token.item()])

universités

### **The Seq2Seq Model**

In [15]:
from models.seq2seq import Seq2Seq
device = torch.device("cpu")

encoder = Encoder(vocab_size = eng_vocab.vocab_size, embedding_dim=256, hidden_size = 512)
decoder = Decoder(vocab_size = fr_vocab.vocab_size, embedding_dim= 256, hidden_size = 512)

model = Seq2Seq(encoder, decoder, device)

In [32]:
input_tensor = sentence_to_tensor(eng_vocab,'i am cold')
input_tensor = input_tensor.unsqueeze(0) 

target_tensor = sentence_to_tensor(fr_vocab,'je suis froid')
target_tensor = target_tensor.unsqueeze(0) 

src = input_tensor
trg = target_tensor

output = model(src,trg)

In [20]:
print(output.shape)
print(trg.shape)

torch.Size([1, 4, 35321])
torch.Size([1, 4])

In [17]:
output = output.view(-1, output.shape[-1])
target = trg.view(-1)

In [18]:
print(trg)
print(trg.shape)

tensor([[ 46, 106, 545,   1]])
torch.Size([1, 4])

In [13]:
print(output.shape)
print(target.shape)

torch.Size([4, 35321])
torch.Size([4])

In [18]:
criterion = torch.nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr = 0.001)

In [19]:
# backpropagation
for i in range(0,25):
    optimizer.zero_grad()
    output = model(src,trg)
    output = output.view(-1, output.shape[-1])
    target = trg.view(-1)
    loss = criterion(output, target)
    print(loss.item())
    loss.backward()
    optimizer.step()
    pred = output.argmax(1)
    for token in pred:
        print(fr_vocab.index2word[token.item()])

10.396927833557129
SOS
cesserait
railleries
provisions
10.29338264465332
SOS
suis
écrismoi
refusé
9.836687088012695
SOS
suis
froid
EOS
9.314943313598633
SOS
suis
froid
EOS
8.756999969482422
SOS
suis
froid
EOS
8.17231559753418
SOS
suis
froid
EOS
7.5656418800354
SOS
suis
froid
EOS
6.940788745880127
SOS
suis
froid
EOS
6.301896095275879
SOS
suis
froid
EOS
5.654910564422607
SOS
suis
froid
EOS
5.0106611251831055
SOS
suis
froid
EOS
4.389815330505371
SOS
suis
froid
EOS
3.8257646560668945
SOS
suis
froid
EOS
3.3577637672424316
SOS
suis
froid
EOS
3.017045021057129
SOS
suis
froid
EOS
2.809523105621338
SOS
suis
froid
EOS
2.704559326171875
SOS
suis
froid
EOS
2.657414197921753
SOS
suis
froid
EOS
2.63683819770813
SOS
suis
froid
EOS
2.6275978088378906
SOS
suis
froid
EOS
2.6232213973999023
SOS
suis
froid
EOS
2.6210618019104004
SOS
suis
froid
EOS
2.619882106781006
SOS
suis
froid
EOS
2.619107246398926
SOS
suis
froid
EOS
2.618734121322632
SOS
suis
froid
EOS

### **Creating Dataset pairs**

In [20]:
pairs = []
for eng, fr in zip(df['English'][:5000], df['French'][:5000]):
    pairs.append((eng,fr))

In [29]:
print((pairs))

[('go', 'va'), ('go', 'marche'), ('go', 'en route'), ('go', 'bouge'), ('hi', 'salut'), ('hi', 'salut'), ('run', 'cours'), ('run', 'courez'), ('run', 'prenez vos jambes à vos cous'), ('run', 'file'), ('run', 'filez'), ('run', 'cours'), ('run', 'fuyez'), ('run', 'fuyons'), ('run', 'cours'), ('run', 'courez'), ('run', 'prenez vos jambes à vos cous'), ('run', 'file'), ('run', 'filez'), ('run', 'cours'), ('run', 'fuyez'), ('run', 'fuyons'), ('who', 'qui'), ('wow', 'ça alors'), ('wow', 'waouh'), ('wow', 'wah'), ('duck', 'à terre'), ('duck', 'baissetoi'), ('duck', 'baissezvous'), ('fire', 'au feu'), ('help', 'à laide'), ('hide', 'cachetoi'), ('hide', 'cachezvous'), ('jump', 'saute'), ('jump', 'saute'), ('stop', 'ça suffit'), ('stop', 'stop'), ('stop', 'arrêtetoi'), ('wait', 'attends'), ('wait', 'attendez'), ('wait', 'attendez'), ('wait', 'attends'), ('wait', 'attendez'), ('wait', 'attends'), ('wait', 'attendez'), ('begin', 'commencez'), ('begin', 'commence'), ('go on', 'poursuis'), ('go on', 'continuez'), ('go on', 'poursuivez'), ('hello', 'bonjour'), ('hello', 'salut'), ('hello', 'bonjour'), ('hello', 'salut'), ('hello', 'bonjour'), ('hello', 'salut'), ('i see', 'je comprends'), ('i see', 'aha'), ('i try', 'jessaye'), ('i won', 'jai gagné'), ('i won', 'je lai emporté'), ('i won', 'j’ai gagné'), ('oh no', 'oh non'), ('relax', 'calmetoi'), ('relax', 'détendstoi'), ('relax', 'détendezvous'), ('relax', 'relaxe max'), ('relax', 'cool raoul'), ('relax', 'du calme'), ('relax', 'relaxe'), ('relax', 'calmezvous'), ('relax', 'détendstoi'), ('relax', 'détendstoi'), ('relax', 'du calme'), ('relax', 'tranquille'), ('shoot', 'tire'), ('shoot', 'tirez'), ('smile', 'souriez'), ('smile', 'souris pour la caméra'), ('smile', 'souriez'), ('sorry', 'pardon'), ('attack', 'attaque'), ('attack', 'attaquez'), ('attack', 'à lattaque'), ('attack', 'à lattaque'), ('buy it', 'achetezla'), ('buy it', 'achètele'), ('buy it', 'achetezle'), ('buy it', 'achètela'), ('cheers', 'santé'), ('cheers', 'à votre santé'), ('cheers', 'merci'), ('cheers', 'tchintchin'), ('eat it', 'mangezle'), ('eat it', 'mangele'), ('exhale', 'expire'), ('get up', 'lèvetoi'), ('get up', 'lèvetoi'), ('get up', 'debout'), ('go now', 'va maintenant'), ('go now', 'allezy maintenant'), ('go now', 'vasy maintenant'), ('got it', 'jai pigé'), ('got it', 'compris'), ('got it', 'aha'), ('got it', 'pigé'), ('got it', 'compris'), ('got it', 'tas capté'), ('hop in', 'monte'), ('hop in', 'montez'), ('hug me', 'serremoi dans tes bras'), ('hug me', 'serrezmoi dans vos bras'), ('i fell', 'je suis tombée'), ('i fell', 'je suis tombé'), ('i fled', 'jai fui'), ('i hunt', 'je chasse'), ('i knit', 'je tricote'), ('i know', 'je sais'), ('i left', 'je suis parti'), ('i left', 'je suis partie'), ('i left', 'je partis'), ('i left', 'je sortis'), ('i lied', 'jai menti'), ('i lost', 'jai perdu'), ('i paid', 'je payais'), ('i paid', 'je payai'), ('i paid', 'j’ai payé'), ('i pass', 'je passe'), ('i quit', 'jarrête'), ('i quit', 'jai arrêté'), ('i swim', 'je nage'), ('im 19', 'jai 19 ans'), ('im ok', 'je vais bien'), ('im ok', 'ça va'), ('inhale', 'inspire'), ('listen', 'écoutez'), ('no way', 'cest pas possible'), ('no way', 'impossible'), ('no way', 'hors de question'), ('no way', 'en aucun cas'), ('no way', 'sans façons'), ('no way', 'mon œil'), ('no way', 'cest hors de question'), ('no way', 'il nen est pas question'), ('no way', 'cest exclu'), ('no way', 'en aucune manière'), ('no way', 'hors de question'), ('no way', 'sans blague'), ('really', 'vraiment'), ('really', 'vrai'), ('really', 'ah bon'), ('really', 'ah vraiment'), ('really', 'vraiment'), ('thanks', 'merci'), ('thanks', 'je te remercie'), ('thanks', 'merci'), ('thanks', 'merci'), ('try it', 'essaie'), ('try it', 'essayez'), ('try it', 'essaye'), ('we try', 'on essaye'), ('we won', 'nous avons gagné'), ('we won', 'nous gagnâmes'), ('we won', 'nous lavons emporté'), ('we won', 'nous lemportâmes'), ('we won', 'on a gagné'), ('ask tom', 'demande à tom'), ('ask him', 'demandelui'), ('awesome', 'fantastique'), ('awesome', 'sensass'), ('awesome', 'trop cool'), ('awesome', 'génial'), ('be calm', 'sois calme'), ('be calm', 'soyez calme'), ('be calm', 'soyez calmes'), ('be cool', 'sois détendu'), ('be fair', 'sois juste'), ('be fair', 'soyez juste'), ('be fair', 'soyez justes'), ('be fair', 'sois équitable'), ('be fair', 'soyez équitable'), ('be fair', 'soyez équitables'), ('be fair', 'sois honnête'), ('be fair', 'sois sincère'), ('be fair', 'soyez honnêtes'), ('be kind', 'sois gentil'), ('be nice', 'sois gentil'), ('be nice', 'sois gentille'), ('be nice', 'soyez gentil'), ('be nice', 'soyez gentille'), ('be nice', 'soyez gentils'), ('be nice', 'soyez gentilles'), ('beat it', 'cassezvous'), ('beat it', 'va te faire foutre'), ('beat it', 'dégage'), ('beat it', 'cassetoi'), ('beat it', 'pars'), ('beat it', 'foutez le camp'), ('beat it', 'fous le camp'), ('beat it', 'pars dici'), ('beat it', 'vat’en'), ('beat it', 'disparais'), ('beat it', 'fiche le camp'), ('beat it', 'tiretoi de là'), ('beat it', 'cassetoi de là'), ('beat it', 'oust'), ('beat it', 'dégage'), ('beat it', 'fiche le camp dici'), ('beat it', 'déguerpissez'), ('beat it', 'bouge'), ('beat it', 'décampe'), ('burn it', 'brûlezle'), ('burn it', 'brûlezla'), ('burn it', 'brûlela'), ('burn it', 'brûlele'), ('bury it', 'enterrezle'), ('bury it', 'enterrele'), ('bury it', 'enterrezla'), ('bury it', 'enterrela'), ('call me', 'appellemoi'), ('call me', 'appelezmoi'), ('call us', 'appellenous'), ('call us', 'appeleznous'), ('come in', 'entrez'), ('come in', 'entre'), ('come in', 'entre'), ('come in', 'entrez'), ('come on', 'allez'), ('come on', 'en avant'), ('come on', 'allons'), ('come on', 'cest pas vrai dis'), ('come on', 'viens'), ('come on', 'venez'), ('come on', 'secouezvous'), ('come on', 'secouetoi'), ('come on', 'allez on y va'), ('come on', 'allez'), ('come on', 'viens'), ('come on', 'venez'), ('drop it', 'laisse tomber'), ('drop it', 'laissez tomber'), ('drop it', 'laissele tomber'), ('drop it', 'laissezle tomber'), ('fold it', 'pliezle'), ('fold it', 'pliele'), ('fold it', 'pliezla'), ('fold it', 'pliela'), ('get tom', 'va chercher tom'), ('get out', 'sors'), ('get out', 'sortez'), ('get out', 'dégage'), ('get out', 'disparais'), ('get out', 'cassetoi'), ('get out', 'dégagez'), ('get out', 'sors'), ('get out', 'sortez'), ('get out', 'dégage'), ('get out', 'disparais'), ('get out', 'du balai'), ('get out', 'fiche le camp'), ('get out', 'oust'), ('get out', 'vers lextérieur'), ('get out', 'fichez le camp'), ('get out', 'sortez'), ('get out', 'décampez'), ('get out', 'décampe'), ('get out', 'sors'), ('get out', 'sortez'), ('get out', 'dégage'), ('get out', 'disparais'), ('get out', 'cassetoi'), ('get out', 'dégagez'), ('get out', 'sors'), ('get out', 'sortez'), ('get out', 'disparais'), ('get out', 'fiche le camp'), ('get out', 'oust'), ('get out', 'sortez'), ('get out', 'bouge'), ('get out', 'décampez'), ('get out', 'décampe'), ('go away', 'dégage'), ('go away', 'pars'), ('go away', 'allezvousen'), ('go away', 'déguerpissez'), ('go away', 'cassezvous'), ('go away', 'bouge'), ('go away', 'décampez'), ('go away', 'décampe'), ('go away', 'va te faire foutre'), ('go away', 'pars'), ('go away', 'dégage'), ('go away', 'fous le camp'), ('go away', 'pars dici'), ('go away', 'vat’en'), ('go away', 'disparais'), ('go away', 'déguerpissez'), ('go away', 'cassezvous'), ('go away', 'bouge'), ('go away', 'décampez'), ('go away', 'décampe'), ('go away', 'allezvousen'), ('go back', 'recule'), ('go home', 'rentre à la maison'), ('go home', 'rentre chez toi'), ('go home', 'rentrez chez vous'), ('go slow', 'va doucement'), ('go slow', 'allez doucement'), ('goodbye', 'adieu'), ('goodbye', 'à la revoyure'), ('goodbye', 'ciao'), ('goodbye', 'ciao'), ('hang on', 'attends un peu'), ('hang on', 'attendez un peu'), ('hang on', 'attendez'), ('hang on', 'tiens bon'), ('hang on', 'tenez bon'), ('hang on', 'attendez'), ('he left', 'il est parti'), ('he runs', 'il court'), ('help me', 'aidemoi'), ('help me', 'à laide'), ('help me', 'aidemoi'), ('help me', 'aidezmoi'), ('help me', 'aidemoi'), ('help us', 'aideznous'), ('help us', 'aidenous'), ('hire me', 'engagezmoi'), ('hire me', 'engagemoi'), ('hire me', 'embauchezmoi'), ('hire me', 'embauchemoi'), ('hold it', 'ne bouge plus'), ('hold it', 'ne bougez plus'), ('hold it', 'restez où vous êtes'), ('hold it', 'attendez'), ('hold on', 'ne quittez pas'), ('hold on', 'attends'), ('hold on', 'ne quitte pas'), ('hold on', 'accrochetoi'), ('hold on', 'tiensbon'), ('hold up', 'tiens bon'), ('hold up', 'tenez bon'), ('how sad', 'comme cest triste'), ('hug tom', 'fais un câlin à tom'), ('i agree', 'je suis du même avis'), ('i cried', 'jai pleuré'), ('i dozed', 'je me suis assoupi'), ('i dozed', 'je me suis assoupie'), ('i drive', 'je conduis'), ('i drove', 'je conduisis'), ('i fired', 'jai tiré'), ('i froze', 'je me suis figé'), ('i froze', 'je me suis figée'), ('i smoke', 'je fume'), ('i snore', 'je ronfle'), ('i stink', 'je pue'), ('i stood', 'je me suis tenu debout'), ('i stood', 'je me suis tenue debout'), ('i swore', 'j’ai promis'), ('i swore', 'j’ai juré'), ('i tried', 'jessayai'), ('i tried', 'jai essayé'), ('i tried', 'jai tenté'), ('i waved', 'j’ai fait signe'), ('ill go', 'jirai'), ('im tom', 'je suis tom'), ('im fat', 'je suis gras'), ('im fat', 'je suis gros'), ('im fit', 'je suis en forme'), ('im hit', 'je suis touché'), ('im hit', 'je suis touchée'), ('im ill', 'je suis malade'), ('im mad', 'je suis fou'), ('im mad', 'je suis folle'), ('im mad', 'je suis en colère'), ('im sad', 'je suis triste'), ('im sad', 'jai un coup de cafard'), ('im sad', 'je suis malheureux'), ('im shy', 'je suis timide'), ('im wet', 'je suis mouillé'), ('im wet', 'je suis mouillée'), ('its me', 'cest bibi'), ('join me', 'rejoignezmoi'), ('join us', 'joignezvous'), ('join us', 'joignezvous à nous'), ('keep it', 'gardele'), ('keep it', 'gardezle'), ('kick it', 'donnelui un coup de pied'), ('kick it', 'donnezlui un coup de pied'), ('kill it', 'tuezle'), ('kill it', 'tuele'), ('kill it', 'tuela'), ('kill it', 'tuezla'), ('kiss me', 'embrassemoi'), ('kiss me', 'embrassezmoi'), ('lie low', 'à terre'), ('lie low', 'au sol'), ('lock it', 'verrouillezle'), ('lock it', 'verrouillele'), ('lock it', 'verrouillezla'), ('lock it', 'verrouillela'), ('look up', 'levez les yeux'), ('look up', 'lève les yeux'), ('me too', 'moi aussi'), ('me too', 'à moi aussi'), ('move on', 'passez à autre chose'), ('move on', 'passe à autre chose'), ('open it', 'ouvrezle'), ('open it', 'ouvrele'), ('open it', 'ouvrela'), ('open it', 'ouvrezla'), ('open up', 'ouvremoi'), ('open up', 'ouvre'), ('pair up', 'faites équipe'), ('perfect', 'parfait'), ('perfect', 'nickel'), ('perfect', 'parfait'), ('pull it', 'tirez dessus'), ('pull it', 'tire dessus'), ('push it', 'appuie dessus'), ('push it', 'poussezle'), ('push it', 'poussele'), ('push it', 'poussezla'), ('push it', 'poussela'), ('see you', 'à plus tard'), ('see you', 'à bientôt'), ('see you', 'à la prochaine'), ('see you', 'ciao'), ('see you', 'à plus'), ('see you', 'ciao'), ('show me', 'montremoi'), ('show me', 'montrezmoi'), ('shut up', 'taisezvous'), ('shut up', 'fermela'), ('shut up', 'taistoi'), ('shut up', 'fermela'), ('shut up', 'la ferme'), ('shut up', 'bouclezla'), ('shut up', 'fermezla'), ('shut up', 'fermela'), ('sign up', 'inscrivezvous'), ('sign up', 'inscristoi'), ('skip it', 'laisse tomber'), ('skip it', 'pas grave'), ('so long', 'à plus tard'), ('take it', 'prendsle'), ('take it', 'prenezle'), ('take it', 'prendsle'), ('take it', 'prenezle'), ('take it', 'prenezle'), ('take it', 'prendsle'), ('tell me', 'dismoi'), ('tell me', 'ditesmoi'), ('tom won', 'tom a gagné'), ('wake up', 'réveilletoi'), ('wake up', 'réveilletoi'), ('wake up', 'réveillezvous'), ('wake up', 'réveilletoi'), ('wake up', 'réveillezvous'), ('wash up', 'lavetoi'), ('wash up', 'lavezvous'), ('we care', 'nous nous en soucions'), ('we know', 'nous savons'), ('we know', 'on sait'), ('we lost', 'nous perdîmes'), ('we lost', 'nous avons perdu'), ('we lost', 'nous fûmes battus'), ('we lost', 'nous fûmes battues'), ('we lost', 'nous fûmes défaits'), ('we lost', 'nous fûmes défaites'), ('we lost', 'nous avons été défaits'), ('we lost', 'nous avons été défaites'), ('we lost', 'nous avons été battus'), ('we lost', 'nous avons été battues'), ('welcome', 'bienvenue'), ('welcome', 'soyez le bienvenu'), ('who ran', 'qui courait'), ('who won', 'qui a gagné'), ('who won', 'qui la emporté'), ('you run', 'tu cours'), ('you win', 'vous avez gagné'), ('aim high', 'visez haut'), ('aim high', 'vise haut'), ('am i fat', 'suisje gros'), ('am i fat', 'suisje grosse'), ('ask them', 'demandeleur'), ('ask them', 'demandezleur'), ('back off', 'recule'), ('back off', 'reculez'), ('back off', 'cassezvous'), ('back off', 'recule'), ('back off', 'reculez'), ('back off', 'retiretoi'), ('back off', 'retirezvous'), ('back off', 'cassezvous'), ('be a man', 'sois un homme'), ('be a man', 'soyez un homme'), ('be brave', 'soyez courageux'), ('be brief', 'soyez bref'), ('be brief', 'sois bref'), ('be brief', 'sois brève'), ('be brief', 'soyez brève'), ('be brief', 'soyez brefs'), ('be brief', 'soyez brèves'), ('be quiet', 'tienstoi sage'), ('be still', 'sois calme'), ('be still', 'soyez calme'), ('be still', 'soyez calmes'), ('buzz off', 'cassetoi'), ('call tom', 'appelle tom'), ('call tom', 'appelez tom'), ('can i go', 'je peux y aller'), ('cheer up', 'courage'), ('cheer up', 'courage'), ('cool off', 'détendstoi'), ('cover me', 'couvremoi'), ('cuff him', 'menottezle'), ('drive on', 'avance'), ('drive on', 'avancez'), ('drive on', 'continue à rouler'), ('drive on', 'continuez à rouler'), ('find tom', 'trouve tom'), ('find tom', 'trouvez tom'), ('fix this', 'réparez ceci'), ('fix this', 'répare ça'), ('get away', 'dégage'), ('get away', 'cassetoi'), ('get away', 'pars'), ('get away', 'dégage'), ('get away', 'fous le camp'), ('get away', 'pars dici'), ('get away', 'vat’en'), ('get away', 'écartetoi'), ('get away', 'disparais'), ('get away', 'allezvousen'), ('get away', 'fiche le camp'), ('get away', 'tiretoi de là'), ('get away', 'dégage'), ('get away', 'vaten'), ('get away', 'criss ton camp dicit'), ('get away', 'fichez le camp'), ('get away', 'déguerpissez'), ('get away', 'cassezvous'), ('get away', 'barrezvous'), ('get away', 'barretoi'), ('get away', 'vat’en'), ('get away', 'bouge'), ('get away', 'décampez'), ('get away', 'décampe'), ('get away', 'tu dis n’importe quoi'), ('get away', 'pars'), ('get away', 'partez'), ('get down', 'lâchetoi'), ('get down', 'à terre'), ('get down', 'au sol'), ('get down', 'descends'), ('get down', 'descends'), ('get down', 'descendez'), ('get down', 'lâchetoi'), ('get down', 'lâchezvous'), ('get down', 'à terre'), ('get down', 'au sol'), ('get down', 'descends'), ('get lost', 'va voir ailleurs si jy suis'), ('get lost', 'dégage'), ('get lost', 'va au diable'), ('get lost', 'déguerpissez'), ('get lost', 'cassezvous'), ('get lost', 'bouge'), ('get lost', 'décampez'), ('get lost', 'décampe'), ('get lost', 'va te faire foutre'), ('get lost', 'va te faire voir'), ('get lost', 'fiche le camp'), ('get lost', 'fichez le camp'), ('get lost', 'déguerpissez'), ('get lost', 'cassezvous'), ('get lost', 'bouge'), ('get lost', 'décampez'), ('get lost', 'décampe'), ('get real', 'sois réaliste'), ('get real', 'tu délires'), ('go ahead', 'allez'), ('go ahead', 'vasy'), ('go ahead', 'en avant'), ('go ahead', 'va'), ('go ahead', 'poursuis'), ('go ahead', 'poursuivez'), ('go ahead', 'passe devant'), ('go ahead', 'vasy'), ('go ahead', 'allezy'), ('go ahead', 'continuez'), ('go ahead', 'continue'), ('go ahead', 'allez'), ('go ahead', 'avance'), ('go ahead', 'en avant'), ('go ahead', 'allez'), ('go ahead', 'vasy'), ('go ahead', 'va'), ('go ahead', 'poursuis'), ('go ahead', 'poursuivez'), ('go ahead', 'passe devant'), ('go ahead', 'vasy'), ('go ahead', 'allezy'), ('go ahead', 'continuez'), ('go ahead', 'continue'), ('go ahead', 'allez'), ('go ahead', 'avance'), ('go ahead', 'en route'), ('good job', 'bien joué'), ('good job', 'bon boulot'), ('good job', 'beau travail'), ('good job', 'bravo'), ('grab tom', 'attrape tom'), ('grab tom', 'attrapez tom'), ('grab him', 'attrapele'), ('grab him', 'attrapezle'), ('grab him', 'mettezlui la main dessus'), ('have fun', 'amusetoi bien'), ('have fun', 'amusezvous bien'), ('have fun', 'amusetoi bien'), ('have fun', 'amusezvous bien'), ('he spoke', 'il a parlé'), ('he spoke', 'il a pris la parole'), ('he spoke', 'il sest exprimé'), ('he tries', 'il essaye'), ('hes wet', 'il est mouillé'), ('help tom', 'aide tom'), ('help tom', 'aidez tom'), ('help tom', 'aidez tom'), ('hi guys', 'salut les mecs'), ('hit back', 'riposte'), ('hit back', 'ripostez'), ('how cute', 'comme cest mignon'), ('how cute', 'trop mignon'), ('how cute', 'trop mignonne'), ('how deep', 'quelle profondeur'), ('how nice', 'comme elle est belle'), ('how nice', 'comme cest chouette'), ('how nice', 'comme cest gentil'), ('how nice', 'cest du joli'), ('how nice', 'comme cest agréable'), ('how rude', 'quelle grossièreté'), ('how rude', 'quelle impolitesse'), ('how wise', 'quelle sagesse'), ('hurry up', 'dépêchetoi'), ('hurry up', 'grouille'), ('hurry up', 'pressezvous'), ('hurry up', 'fiça'), ('hurry up', 'magnetoi'), ('hurry up', 'magnezvous'), ('i am tom', 'je suis tom'), ('i cursed', 'jai juré'), ('i did ok', 'je men suis bien sorti'), ('i did ok', 'je men suis bien sortie'), ('i did it', 'je lai fait'), ('i did it', 'cest moi qui lai fait'), ('i failed', 'jai échoué'), ('i forgot', 'jai oublié'), ('i get it', 'jai compris'), ('i goofed', 'jai fait une gaffe'), ('i goofed', 'jai fait une bourde'), ('i goofed', 'jai fait une boulette'), ('i got it', 'jai compris'), ('i got it', 'jai capté'), ('i helped', 'jai aidé'), ('i jumped', 'jai sauté'), ('i looked', 'j’ai regardé'), ('i moaned', 'j’ai râlé'), ('i nodded', 'j’ai fait signe de la tête'), ('i obeyed', 'j’ai obéi'), ('i phoned', 'je téléphonai'), ('i phoned', 'jai téléphoné'), ('i refuse', 'je refuse'), ('i refuse', 'je le refuse'), ('i rested', 'je me suis reposé'), ('i rested', 'je me suis reposée'), ('i saw it', 'je lai vu'), ('i saw it', 'je l’ai vu'), ('i sighed', 'j’ai soupiré'), ('i smiled', 'jai souri'), ('i stayed', 'je suis resté'), ('i stayed', 'je suis restée'), ('i talked', 'j’ai parlé'), ('i use it', 'je lutilise'), ('i use it', 'jen fais usage'), ('i use it', 'je men sers'), ('ill pay', 'je paierai'), ('ill pay', 'je paie'), ('ill try', 'je vais essayer'), ('ill try', 'jessaierai'), ('im back', 'je suis revenu'), ('im back', 'me revoilà'), ('im bald', 'je suis chauve'), ('im busy', 'je suis occupé'), ('im busy', 'je suis occupée'), ('im calm', 'je suis calme'), ('im cold', 'jai froid'), ('im cool', 'je suis détendu'), ('im cool', 'je suis détendue'), ('im deaf', 'je suis sourd'), ('im deaf', 'je suis sourde'), ('im done', 'jen ai fini'), ('im fair', 'je suis juste'), ('im fair', 'jai la peau claire'), ('im fair', 'jai le teint clair'), ('im fast', 'je suis rapide'), ('im fine', 'tout va bien'), ('im fine', 'je vais bien'), ('im fine', 'ça va'), ('im free', 'je suis libre'), ('im free', 'je suis libre'), ('im free', 'je suis disponible'), ('im full', 'je suis repu'), ('im full', 'je suis rassasié'), ('im game', 'jen suis'), ('im game', 'je suis de la partie'), ('im glad', 'je suis content'), ('im good', 'je vais bien'), ('im good', 'je suis bon'), ('im home', 'je suis chez moi'), ('im late', 'je suis en retard'), ('im lazy', 'je suis paresseux'), ('im lazy', 'je suis fainéant'), ('im lazy', 'je suis paresseuse'), ('im lazy', 'je suis fainéante'), ('im lost', 'je suis paumé'), ('im lost', 'je suis perdue'), ('im okay', 'je vais bien'), ('im okay', 'je me porte bien'), ('im rich', 'je suis riche'), ('im safe', 'je suis en sécurité'), ('im sick', 'je suis malade'), ('im sure', 'jen suis certain'), ('im sure', 'je suis certain'), ('im sure', 'jen suis sûr'), ('im sure', 'je

In [21]:
from preprocessing.dataset import TranslationDataset
dataset = TranslationDataset(pairs, eng_vocab, fr_vocab)

src, trg = dataset[0]

print(src)
print(trg)

tensor([4, 1])
tensor([4, 1])

### **Creating DataLoader**

In [22]:
from torch.utils.data import DataLoader
from preprocessing.dataset import TranslationDataset, collate_fn

In [ ]:
dataset = TranslationDataset(pairs, eng_vocab, fr_vocab)

dataloader = DataLoader(
    dataset,
    batch_size = 32,
    shuffle = True,
    collate_fn = collate_fn
)

In [24]:
for src, trg in dataloader:
    print(src.shape)
    print(trg.shape)
    break

torch.Size([32, 4])
torch.Size([32, 5])

### **Full Training Loop**

In [25]:
PAD_IDX = 2 # the tokens which should be ignored and must not affect the training process

criterion = torch.nn.CrossEntropyLoss(ignore_index = PAD_IDX)
optimizer = torch.optim.Adam(model.parameters(), lr = 0.001)

In [27]:
from training.train import train

train(model, num_epochs = 10, dataloader = dataloader, optimizer = optimizer, criterion = criterion)

Epoch: 1, Loss: 6.5283
Epoch: 2, Loss: 5.5478
Epoch: 3, Loss: 5.3128
Epoch: 4, Loss: 5.1442
Epoch: 5, Loss: 5.0595
Epoch: 6, Loss: 4.9781
Epoch: 7, Loss: 4.9649
Epoch: 8, Loss: 4.9067
Epoch: 9, Loss: 4.8927
Epoch: 10, Loss: 4.8558

### **TranslateSentence Function**

In [ ]:
def translate_sentence(sentence):

    src = sentence_to_tensor(eng_vocab, sentence)
    src = (src.unsqueeze(0)).to(device)

    encoder_outputs, hidden = encoder(src)

    decoder_input =( torch.tensor([[fr_vocab.word2index["SOS"]]]).to(device))

    translated_tokens = []

    for _ in range(20):

        output, hidden, attn_weights = decoder(decoder_input, hidden, encoder_outputs)

        pred_token = output.argmax(2)

        pred_idx = pred_token.item()

        if pred_idx == fr_vocab.word2index["EOS"]:
            break

        translated_tokens.append(fr_vocab.index2word[pred_idx])

        decoder_input = pred_token

    return " ".join(translated_tokens)

In [42]:
translate_sentence("hii there")

''